dbt_elevate_playground:
  target: dev
  outputs:
    dev:
      job_execution_timeout_seconds: 600
      job_retries: 1
      location: EU
      method: oauth
      project: elevate-eng-lab-core
      priority: interactive
      schema: "dbt_dataset_test"
      database: elevate-eng-lab-core
      threads: 10
      type: bigquery
      impersonate_service_account: dbt-lab@elevate-eng-lab-core.iam.gserviceaccount.com
      execution_project: elevate-eng-lab-core
