name: "dbt_elevate_playground"
version: "1.0.0"

require-dbt-version: ">=0.18.0"
config-version: 2

profile: "dbt_elevate_playground"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: "logs"
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  gcp_projects:
    lab:
      dev: elevate-eng-lab-core


seeds:
  dbt_elevate_playground:
    schema: "dbt_seed"

