name: dbt-validate

on:
  pull_request:
    branches:
      - dev
      - main
      - prod

  workflow_dispatch:

jobs:
  validate-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv dbt-env
          source dbt-env/bin/activate
          pip install dbt-core dbt-bigquery sqlfluff

      - name: Set-Up DBT_PROFILES_DIR
        run: |
          export DBT_PROFILES_DIR=$(pwd)/.github
          echo "DBT_PROFILES_DIR=$(pwd)/.github" >> $GITHUB_ENV

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials: true
          export_environment_variables: true
          cleanup_credentials: true
          access_token_lifetime: 3600
          retries: 0
          
      - name: Validate dbt
        env:
          DBT_PROFILES_DIR: ${{ env.DBT_PROFILES_DIR }}
        run: |
          source dbt-env/bin/activate
          dbt deps
          dbt debug
          dbt run
          dbt test

      - name: Cleanup
        run: |
          deactivate || true
          rm -rf dbt-env
