name: dbt-validate

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  validate-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv dbt-env
          source dbt-env/bin/activate
          pip install dbt-core dbt-bigquery sqlfluff

      - name: Set-Up DBT_PROFILES_DIR
        run: |
          export DBT_PROFILES_DIR=$(pwd)/.github
          echo "DBT_PROFILES_DIR=$(pwd)/.github" >> $GITHUB_ENV

      - name: Debug all env variables
        run: |
          echo "List all env variables"
          env

      - name: Debug DBT_PROFILES_DIR
        run: |
          echo "Value of DBT_PROFILES_DIR: $DBT_PROFILES_DIR"
          echo "GITHUB_ENV contains:"
          cat $GITHUB_ENV

      - name: Verifying profiles.yml
        env:
          DBT_PROFILES_DIR: ${{ env.DBT_PROFILES_DIR }}
        run: |
          ls -la "$(DBT_PROFILES_DIR)/profiles.yml"

      - name: Lint SQL
        run: |
          source dbt-env/bin/activate
          sqlfluff lint .
